language: minimal

services:
  - docker

before_install:
  - docker pull  silex/emacs:26.1-alpine

script:
  - docker run -v $(pwd):/root/.emacs.d -it -w /root/.emacs.d silex/emacs:26.1-alpine emacs -Q --script init.el 
