#+TITLE: Emacs configuration
#+AUTHOR: Carl Düvel
#+EMAIL: c.a.duevel@gmail.com 

* Dependency management

** Define package repositories(archives)

#+BEGIN_SRC emacs-lisp
(require 'package)

(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ;("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))

#+END_SRC

** Packages to be installed

#+BEGIN_SRC emacs-lisp
(defvar my-packages '(evil
                      evil-escape
                      evil-leader
                      exec-path-from-shell
                      org-bullets
                      popup
                      synosaurus
                      which-key
                      zenburn-theme
                      magit))

#+END_SRC 
Emacs dependencies/libraries are managed via the internal [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Packages.html#Packages][package
management system]]. To initially install packages, open
=~/.emacs.d/init.el=, refresh your package list with =M-x
package-refresh-contents= and install everything using =M-x
eval-buffer=.

#+BEGIN_SRC emacs-lisp
  (dolist (p my-packages)
    (unless (package-installed-p p)
      (package-refresh-contents)
      (package-install p))
    (add-to-list 'package-selected-packages p))
#+END_SRC

* Configuration of built-in features
** Gargabe Collection
   
Allow 20MB of memory (instead of 0.76MB) before calling garbage
collection. This means GC runs less often, which speeds up some
operations.

#+BEGIN_SRC emacs-lisp
  (setq gc-cons-threshold 20000000)
#+END_SRC

** Auto-Save in =/tmp=

Store backups and auto-saved files in =TEMPORARY-FILE-DIRECTORY= (which
defaults to /tmp on Unix), instead of in the same directory as the
file.

#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist
        `((".*" . ,temporary-file-directory)))
  (setq auto-save-file-name-transforms
        `((".*" ,temporary-file-directory t)))
#+END_SRC

** Always follow symlinks
   When opening a file, always follow symlinks.

#+BEGIN_SRC emacs-lisp
  (setq vc-follow-symlinks t)
#+END_SRC

** Sentences have one space after a period
Don't assume that sentences should have two spaces after
periods.

#+BEGIN_SRC emacs-lisp
  (setq sentence-end-double-space nil)
#+END_SRC

** Confirm before closing Emacs
#+BEGIN_SRC emacs-lisp
  (setq confirm-kill-emacs 'y-or-n-p)
#+END_SRC

** =dired-mode=

Ability to use =a= to visit a new directory or file in =dired= instead
of using =RET=. =RET= works just fine, but it will create a new buffer
for /every/ interaction whereas =a= reuses the current buffer.

#+BEGIN_SRC emacs-lisp
  (put 'dired-find-alternate-file 'disabled nil)
#+END_SRC

Human readable units

#+BEGIN_SRC emacs-lisp
  (setq-default dired-listing-switches "-alh")
#+END_SRC

** Ask =y/n= instead of =yes/no=
   This is a favorable shorthand.
#+BEGIN_SRC emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC
** Auto revert files on change
When something changes a file, automatically refresh the
buffer containing that file so they can't get out of sync.

#+BEGIN_SRC emacs-lisp
(global-auto-revert-mode t)
#+END_SRC
** Disable startup message

#+BEGIN_SRC emacs-lisp
  (setq inhibit-splash-screen t)
  (setq inhibit-startup-message t)
#+END_SRC

** Automatic Line Breaks
#+BEGIN_SRC emacs-lisp
  (add-hook 'text-mode-hook 'auto-fill-mode)
#+END_SRC

** Disable scroll bar
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
#+END_SRC

** Disable menu bar
#+BEGIN_SRC emacs-lisp
;(menu-bar-mode -1)
#+END_SRC

** Disable tool bar
#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
#+END_SRC

** Remember the cursor position of files when reopening them

#+BEGIN_SRC emacs-lisp
  (setq save-place-file "~/.emacs.d/saveplace")
  (setq-default save-place t)
#+END_SRC

** Custom-File

#+BEGIN_SRC emacs-lisp
(setq custom-file "~/.emacs.d/custom-settings.el")
(load custom-file t)
#+END_SRC
** Put pointer to help window immideatly
#+BEGIN_SRC emacs-lisp
(setq help-window-select t)
#+END_SRC
** Remember the cursor position of files when reopening them

#+BEGIN_SRC emacs-lisp
  (setq save-place-file "~/.emacs.d/saveplace")
  (setq-default save-place t)
#+END_SRC

** Custom-File
#+BEGIN_SRC emacs-lisp
(setq custom-file "~/.emacs.d/custom-settings.el")
(load custom-file t)
#+END_SRC

** Org-mode
*** Exports
Exports to markdown are useful.
#+BEGIN_SRC emacs-lisp
(require 'ox-md)
#+END_SRC

*** Display preferences

Show an outline of pretty bullets instead of a list of asterisks.
#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook 'org-bullets-mode)
#+END_SRC

Show a little downward-pointing arrow instead of the usual ellipsis
(=...=) that org displays when there's stuff under a header.

#+BEGIN_SRC emacs-lisp
  (setq org-ellipsis "⤵")
#+END_SRC

When editing org-files with source-blocks, we want the source blocks to be themed as they would in their native mode.

#+BEGIN_SRC emacs-lisp
(setq org-src-fontify-natively t
    org-src-tab-acts-natively t
    org-confirm-babel-evaluate nil
    org-edit-src-content-indentation 0)
#+END_SRC

Basic setup:



#+BEGIN_SRC emacs-lisp
(require 'org)

(setq gtd-dir "~/org/gtd/")
(setq inbox-file (concat gtd-dir "inbox.org"))
(setq gtd-file (concat gtd-dir "gtd.org"))
(setq tickler-file (concat gtd-dir "tickler.org"))
(setq org-agenda-files (list
                         inbox-file
                         gtd-file
                         tickler-file))

(setq org-default-notes-file  inbox-file)

(setq org-todo-keywords
            '((sequence "TODO" "|" "DONE")
              (sequence "PROJECT" "AGENDA" "|" "MINUTES")
              (sequence "WAITING" "|" "PROGRESS")))

(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key "\C-cl" 'org-store-link)

(setq org-refile-targets '((org-agenda-files :maxlevel . 3)))
(setq org-refile-use-outline-path 'file)

(setq org-agenda-custom-commands 
         '(("h" "@home" tags-todo "@home")
         ("c" "@computer" tags-todo "@computer")
         ("H" "+hasi" tags-todo "+hasi")
         ("p" "@phone" tags-todo "@phone")
         ("b" "@BO" tags-todo "@BO")))                           

(add-hook 'org-mode-hook 'org-indent-mode)

#+END_SRC
Org Capture Templates are explained [[http://orgmode.org/manual/Capture-templates.html][here]], Org Template expansion [[http://orgmode.org/manual/Template-expansion.html#Template-expansion][here.]]
#+BEGIN_SRC emacs-lisp
(define-key global-map "\C-cc" 'org-capture)

(setq org-capture-templates '(("t" "Todo [inbox]" entry
                               (file+headline (concat gtd-dir "inbox.org") "Tasks")
                               "* TODO %i%?")
                              ("T" "Tickler" entry
                               (file+headline (concat gtd-dir "tickler.org") "Tickler")
                               "* %i%? \n %U")))

#+END_SRC

*** TODO Can I auto format embedded lisp code?

** ido completion engine
=ido= stands for /interactivly DO things/ so it means autocompletion
for many functions like find-file or switch-buffer.
#+BEGIN_SRC emacs-lisp
  (ido-mode t)
  (ido-everywhere t)
  (setq ido-enable-flex-matching t)
#+END_SRC

** Flyspell
Order corrections by likeliness, not by the default of alphabetical
ordering.

#+BEGIN_SRC emacs-lisp
(setq flyspell-sort-corrections nil)
#+END_SRC

Do not print messages for every word (when checking the entire
buffer). This is a major performance gain.
#+BEGIN_SRC emacs-lisp
(setq flyspell-issue-message-flag nil)
#+END_SRC

Switch between German and English dictionaries.
Those were installed with ~apt install ingerman iamerican-large~

#+BEGIN_SRC emacs-lisp
  (defun flyspell-switch-dictionary()
    "Switch between German and English dictionaries"
    (interactive)
    (let* ((dic ispell-current-dictionary)
           (change (if (string= dic "deutsch") "english" "deutsch")))
      (ispell-change-dictionary change)
      (message "Dictionary switched from %s to %s" dic change)))
#+END_SRC

Switch on flyspell automatically in some major modes.
#+BEGIN_SRC emacs-lisp
  (add-hook 'text-mode-hook 'flyspell-mode)
  (add-hook 'org-mode-hook 'flyspell-mode)
#+END_SRC

Skip source code in org mode documents.

#+BEGIN_SRC emacs-lisp
(add-to-list 'ispell-skip-region-alist '("^#+BEGIN_SRC" . "^#+END_SRC"))
#+END_SRC

* Configuration of external packages
** Set $MANPATH, $PATH and exec-path from shell even when started from GUI helpers like =dmenu= or =Spotlight=
#+BEGIN_SRC emacs-lisp
(exec-path-from-shell-initialize)
#+END_SRC
** Leader Mode Config
#+BEGIN_SRC emacs-lisp
  (require 'evil-leader)
  (global-evil-leader-mode)
  (evil-leader/set-leader ",")
  (evil-leader/set-key
    "w" 'basic-save-buffer
    "f" 'find-file
    "b" 'evil-buffer
    "a" 'org-archive-subtree-default
    "i" 'org-clock-in
    "o" 'org-clock-out
    "q" 'evil-quit)
#+END_SRC
** Evil mode

Vim emulation for emacs.

#+BEGIN_SRC emacs-lisp
(evil-mode t)
#+END_SRC

Escape modes in evil with jk instead of Esc.

#+BEGIN_SRC emacs-lisp
(setq-default evil-escape-key-sequence "jk")
(setq-default evil-escape-delay 0.2)
(evil-escape-mode)
#+END_SRC

** Custom theme

#+BEGIN_SRC emacs-lisp
(load-theme 'zenburn t)
#+END_SRC

** Magit

Magit is an interface to the version control system Git.

*** Configuration

Create shortcut for =Magit=.

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-x g") 'magit-status)
#+END_SRC

**** Start the commit buffer in evil normal mode

#+BEGIN_SRC emacs-lisp
  (add-hook 'with-editor-mode-hook 'evil-normal-state)
#+END_SRC

** Which Key
  =which-key= displays available keybindings in a popup.

#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook 'which-key-mode)
  (add-hook 'cider-mode-hook 'which-key-mode)
#+END_SRC

** Thesaurus
A thesaurus is provided by the ~synosaurus~ package.
The default backend is wordnet, an offline English thesaurus.
We also install the popup library to have the options presented this
way.
#+BEGIN_SRC emacs-lisp
(setq synosaurus-choose-method 'popup)
#+END_SRC
The default keybinding of ~synosaurus~ clashes with org-mode.
#+BEGIN_SRC emacs-lisp
(evil-leader/set-key "t" 'synosaurus-choose-and-replace)
#+END_SRC



